### ISSUE TITLE
CC-BY-4.0-as-licence-for-GAW-data-hosted-by-GAW-WDCs

### ISSUE THREAD

**Issue by joergklausen** [wmo-cop/et-wdc#19]
Discussion forum for feedback on the CC-BY-4.0 licencing for GAW WDCs. The document can be found at https://github.com/wmo-cop/et-wdc/wiki/CC-BY-4.0-as-licence-for-GAW-data-hosted-by-GAW-WDCs.

**Comment by ejwelton** [comment]
Could I ask for a clarification/explanation please:
I license can only be applied to something that has been patented or copyrighted, the former does not apply in this case. For data that are open (either no license or CC0) that also implies there is no copyright on the data. I was under the impression that the CC license cannot be applied to data that are not copyrighted. A license also can only be granted by the owner of said data, which for most data submitted to the WDCs is not the organization running the WDC. So I do not understand how WDCs would be able to apply a CC-BY license to a vast amount of the data being submitted to them. I am missing something here?

**Comment by joergklausen** [comment]
Issue resolved after document passed by SSC EPAC.
