### ISSUE TITLE
AI2019-4: MPLNet WMDR XML files

### ISSUE THREAD

**Issue by joergklausen** [wmo-cop/et-wdc#4]
Send example of metadata to be encoded in WMDR XML to MeteoSwiss. (Judd Welton, asap). Review information on WIGOS metadata and elements/variables.

**Comment by ejwelton** [comment]
example of MPLNET metadata has been provided to MeteoSwiss

**Comment by ejwelton** [comment]
review of WIGOS metadata and elements/variables ongoing

**Comment by ejwelton** [comment]
Discussions and plans have begun with Drasko. I am building a netcdf metadata file for him with basic information, and he will develop translation app.
